spring:
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
talkJSAppKey: ${TALK_JS_APP_KEY}
MAPBOX_API_KEY: ${MAPBOX_API_KEY}
FILESTACK_API_KEY: ${FILESTACK_API_KEY}